import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../../flutter_flow/flutter_flow_theme.dart';
import '../../../flutter_flow/flutter_flow_util.dart';
import '../../../flutter_flow/flutter_flow_widgets.dart';

class AiRecipeOnboardingWidget extends StatefulWidget {
  const AiRecipeOnboardingWidget({super.key});

  @override
  State<AiRecipeOnboardingWidget> createState() =>
      _AiRecipeOnboardingWidgetState();
}

class _AiRecipeOnboardingWidgetState extends State<AiRecipeOnboardingWidget> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: double.infinity,
        height: double.infinity,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            colors: [
              FlutterFlowTheme.of(context).primary,
              FlutterFlowTheme.of(context).secondary,
            ],
            stops: const [0.0, 1.0],
            begin: const AlignmentDirectional(0.0, -1.0),
            end: const AlignmentDirectional(0, 1.0),
          ),
        ),
        child: SafeArea(
          child: Padding(
            padding: const EdgeInsetsDirectional.fromSTEB(24.0, 0.0, 24.0, 0.0),
            child: Column(
              mainAxisSize: MainAxisSize.max,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                // Logo and Icon
                Container(
                  width: 120.0,
                  height: 120.0,
                  decoration: BoxDecoration(
                    color: Colors.white.withOpacity(0.1),
                    borderRadius: BorderRadius.circular(60.0),
                  ),
                  child: const Icon(
                    Icons.restaurant_menu,
                    color: Colors.white,
                    size: 60.0,
                  ),
                ),

                const SizedBox(height: 32.0),

                // Title
                Text(
                  'AI Recipe Creator',
                  style: GoogleFonts.pacifico(
                    fontSize: 32.0,
                    fontWeight: FontWeight.w400,
                    color: Colors.white,
                  ),
                ),

                const SizedBox(height: 16.0),

                // Subtitle
                Text(
                  'Transform your ingredients into delicious meals with the power of AI',
                  textAlign: TextAlign.center,
                  style: GoogleFonts.poppins(
                    fontSize: 16.0,
                    fontWeight: FontWeight.w300,
                    color: Colors.white.withOpacity(0.9),
                    height: 1.5,
                  ),
                ),

                const SizedBox(height: 48.0),

                // Features List
                Column(
                  children: [
                    _buildFeatureItem(
                      icon: Icons.camera_alt,
                      title: 'Upload Photos',
                      description:
                          'Take photos of your ingredients or upload from gallery',
                    ),
                    const SizedBox(height: 20.0),
                    _buildFeatureItem(
                      icon: Icons.text_fields,
                      title: 'Describe Ingredients',
                      description: 'Type what ingredients you have available',
                    ),
                    const SizedBox(height: 20.0),
                    _buildFeatureItem(
                      icon: Icons.smart_toy,
                      title: 'AI Magic',
                      description: 'Get personalized recipes generated by AI',
                    ),
                    const SizedBox(height: 20.0),
                    _buildFeatureItem(
                      icon: Icons.favorite,
                      title: 'Save Favorites',
                      description: 'Save your favorite AI-generated recipes',
                    ),
                  ],
                ),

                const SizedBox(height: 48.0),

                // CTA Button
                FFButtonWidget(
                  onPressed: () {
                    context.pushNamed('AiRecipeSearch');
                  },
                  text: 'Create Your Recipe Now!',
                  options: FFButtonOptions(
                    width: double.infinity,
                    height: 56.0,
                    padding: const EdgeInsetsDirectional.fromSTEB(
                        0.0, 0.0, 0.0, 0.0),
                    iconPadding: const EdgeInsetsDirectional.fromSTEB(
                        0.0, 0.0, 0.0, 0.0),
                    color: Colors.white,
                    textStyle: GoogleFonts.poppins(
                      fontSize: 16.0,
                      fontWeight: FontWeight.w600,
                      color: FlutterFlowTheme.of(context).primary,
                    ),
                    elevation: 0.0,
                    borderSide: const BorderSide(
                      color: Colors.transparent,
                      width: 1.0,
                    ),
                    borderRadius: BorderRadius.circular(28.0),
                  ),
                ),

                const SizedBox(height: 24.0),

                // Powered by text
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text(
                      'Powered by ',
                      style: GoogleFonts.poppins(
                        fontSize: 12.0,
                        color: Colors.white.withOpacity(0.7),
                      ),
                    ),
                    Text(
                      'Google Gemini AI',
                      style: GoogleFonts.poppins(
                        fontSize: 12.0,
                        fontWeight: FontWeight.w600,
                        color: Colors.white,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildFeatureItem({
    required IconData icon,
    required String title,
    required String description,
  }) {
    return Row(
      children: [
        Container(
          width: 48.0,
          height: 48.0,
          decoration: BoxDecoration(
            color: Colors.white.withOpacity(0.1),
            borderRadius: BorderRadius.circular(24.0),
          ),
          child: Icon(
            icon,
            color: Colors.white,
            size: 24.0,
          ),
        ),
        const SizedBox(width: 16.0),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                title,
                style: GoogleFonts.poppins(
                  fontSize: 16.0,
                  fontWeight: FontWeight.w600,
                  color: Colors.white,
                ),
              ),
              Text(
                description,
                style: GoogleFonts.poppins(
                  fontSize: 14.0,
                  fontWeight: FontWeight.w300,
                  color: Colors.white.withOpacity(0.8),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
