import 'dart:convert';
import 'package:http/http.dart' as http;

/// Test script để gọi sync API trực tiếp
void main() async {
  print('🧪 Testing AI Recipe Sync API...');

  // Sample AI recipe data để test sync
  final sampleRecipe = {
    "id": "test_ai_recipe_${DateTime.now().millisecondsSinceEpoch}",
    "title": "AI Generated Chocolate Cake",
    "description":
        "Delicious chocolate cake generated by AI assistant. Perfect for dessert lovers with rich cocoa flavor and moist texture.",
    "ingredients": [
      "2 cups all-purpose flour",
      "3/4 cup unsweetened cocoa powder",
      "2 cups granulated sugar",
      "2 teaspoons baking soda",
      "1 teaspoon baking powder",
      "1 teaspoon salt",
      "2 large eggs",
      "1 cup buttermilk",
      "1 cup strong black coffee, cooled",
      "1/2 cup vegetable oil",
      "1 teaspoon vanilla extract"
    ],
    "instructions": [
      "Preheat oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.",
      "In a large bowl, whisk together flour, cocoa powder, sugar, baking soda, baking powder, and salt.",
      "In another bowl, beat eggs, then stir in buttermilk, coffee, oil, and vanilla.",
      "Pour wet ingredients into dry ingredients and mix until well combined.",
      "Divide batter evenly between prepared pans.",
      "Bake for 30-35 minutes or until a toothpick inserted in center comes out clean.",
      "Cool in pans for 10 minutes, then turn out onto wire racks to cool completely.",
      "Frost with your favorite chocolate frosting when completely cool."
    ],
    "cuisine": "Dessert",
    "preparationTime": 20,
    "cookingTime": 45,
    "servings": 12,
    "estimatedCalories": 320.0,
    "difficulty": "Medium",
    "tags": ["dessert", "chocolate", "cake", "ai-generated"],
    "imageUrl": "https://via.placeholder.com/400x300?text=AI+Chocolate+Cake",
    "createdAt": DateTime.now().toIso8601String(),
  };

  // Test sync API call
  await testSyncAPI([sampleRecipe]);
}

/// Test gọi sync API
Future<void> testSyncAPI(List<Map<String, dynamic>> recipes) async {
  try {
    print('📡 Sending sync request to backend...');
    print('   URL: http://localhost:8190/api/syncSavedAiRecipes');
    print('   Recipes count: ${recipes.length}');

    final response = await http.post(
      Uri.parse('http://localhost:8190/api/syncSavedAiRecipes'),
      headers: {
        'Content-Type': 'application/json',
        'User-Agent': 'Flutter-Test-Client/1.0',
      },
      body: json.encode({
        'recipes': recipes,
        'userId': 'test_user_flutter_app',
        'deviceInfo': {
          'platform': 'flutter',
          'version': '1.0.0',
          'timestamp': DateTime.now().toIso8601String(),
        }
      }),
    );

    print('');
    print('📈 Response received:');
    print('   Status Code: ${response.statusCode}');
    print('   Response Body: ${response.body}');

    if (response.statusCode == 200) {
      final responseData = json.decode(response.body);
      print('');
      print('✅ Sync successful!');
      print('   Synced recipes: ${responseData['syncedCount'] ?? 'N/A'}');
      print('   Check admin panel: http://localhost:8190/saved-ai-recipes');
    } else {
      print('');
      print('❌ Sync failed!');
      print('   Error: ${response.body}');
    }
  } catch (e) {
    print('');
    print('💥 Error during sync test:');
    print('   $e');
    print('');
    print('🔧 Make sure backend server is running on port 8190');
  }
}
