import 'dart:convert';
import 'package:shared_preferences/shared_preferences.dart';
import 'lib/ai_recipe_generator/domain/entities/ai_meal.dart';

/// Test script để thêm sample AI recipe và test sync function
void main() async {
  print('🧪 Testing AI Recipe Sync...');

  // Thêm sample AI recipe vào local storage
  await addSampleAIRecipe();

  print('✅ Sample AI recipe added to local storage');
  print('📱 Open the Flutter app and check if sync works!');
}

/// Thêm một sample AI recipe vào SharedPreferences
Future<void> addSampleAIRecipe() async {
  final prefs = await SharedPreferences.getInstance();

  // Tạo sample AI recipe
  final sampleRecipe = AIMeal(
    id: 'test_ai_recipe_${DateTime.now().millisecondsSinceEpoch}',
    title: 'AI Generated Chocolate Cake',
    description:
        'Delicious chocolate cake generated by AI assistant. Perfect for dessert lovers with rich cocoa flavor and moist texture.',
    ingredients: [
      '2 cups all-purpose flour',
      '3/4 cup unsweetened cocoa powder',
      '2 cups granulated sugar',
      '2 teaspoons baking soda',
      '1 teaspoon baking powder',
      '1 teaspoon salt',
      '2 large eggs',
      '1 cup buttermilk',
      '1 cup strong black coffee, cooled',
      '1/2 cup vegetable oil',
      '1 teaspoon vanilla extract'
    ],
    instructions: [
      'Preheat oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.',
      'In a large bowl, whisk together flour, cocoa powder, sugar, baking soda, baking powder, and salt.',
      'In another bowl, beat eggs, then stir in buttermilk, coffee, oil, and vanilla.',
      'Pour wet ingredients into dry ingredients and mix until well combined.',
      'Divide batter evenly between prepared pans.',
      'Bake for 30-35 minutes or until a toothpick inserted in center comes out clean.',
      'Cool in pans for 10 minutes, then turn out onto wire racks to cool completely.',
      'Frost with your favorite chocolate frosting when completely cool.'
    ],
    cuisine: 'Dessert',
    preparationTime: 20,
    cookingTime: 45,
    servings: 12,
    estimatedCalories: 320.0,
    difficulty: 'Medium',
    tags: ['dessert', 'chocolate', 'cake', 'ai-generated'],
    imageUrl: 'https://via.placeholder.com/400x300?text=AI+Chocolate+Cake',
    createdAt: DateTime.now(),
  );

  // Lấy danh sách recipes hiện tại (nếu có)
  final recipesJson = prefs.getString('ai_recipes');
  List<Map<String, dynamic>> recipesList = [];

  if (recipesJson != null) {
    final List<dynamic> existingRecipes = json.decode(recipesJson);
    recipesList = existingRecipes.cast<Map<String, dynamic>>();
  }

  // Thêm recipe mới
  recipesList.add(sampleRecipe.toJson());

  // Lưu lại vào SharedPreferences
  await prefs.setString('ai_recipes', json.encode(recipesList));

  print('📝 Sample recipe added:');
  print('   Title: ${sampleRecipe.title}');
  print('   Ingredients: ${sampleRecipe.ingredients.length} items');
  print('   Instructions: ${sampleRecipe.instructions.length} steps');
  print('   Ready for sync to admin panel!');
}
