// Insert realistic saved AI recipes data (như từ mobile app)
require('dotenv').config();
require('./config/conn');
const savedAiRecipeModel = require('./model/savedAiRecipeModel');
const userModel = require('./model/userModel');
const mongoose = require('mongoose');

// Mobile app users
const mobileUsers = [
    {
        name: "Food Lover",
        email: "foodie_lover@gmail.com",
        phone: "123-456-0001"
    },
    {
        name: "Chef Mario",
        email: "chef_mario@hotmail.com", 
        phone: "123-456-0002"
    },
    {
        name: "Korean Food Fan",
        email: "k_food_fan@yahoo.com",
        phone: "123-456-0003"
    },
    {
        name: "Healthy Eater",
        email: "healthy_eater@gmail.com",
        phone: "123-456-0004"
    },
    {
        name: "Sweet Tooth",
        email: "sweet_tooth@outlook.com",
        phone: "123-456-0005"
    },
    {
        name: "Vietnamese Food Lover",
        email: "viet_food_lover@gmail.com",
        phone: "123-456-0006"
    }
];

// Realistic AI recipes data như từ Flutter app
const mobileAppAiRecipes = [
    {
        title: "Spicy Thai Basil Chicken",
        description: "Authentic Thai dish with fragrant basil, chilies, and tender chicken pieces. Generated by AI based on traditional Thai cooking methods.",
        ingredients: [
            "500g chicken thigh, diced",
            "3 cloves garlic, minced", 
            "2 red chilies, sliced",
            "1 cup Thai holy basil leaves",
            "2 tbsp vegetable oil",
            "2 tbsp fish sauce",
            "1 tbsp dark soy sauce",
            "1 tsp sugar",
            "1 bell pepper, sliced",
            "Steamed jasmine rice for serving"
        ],
        instructions: [
            "Heat oil in a wok over high heat until smoking",
            "Add garlic and chilies, stir-fry for 30 seconds until fragrant",
            "Add diced chicken and cook for 3-4 minutes until nearly done", 
            "Add bell pepper and stir-fry for 1 minute",
            "Season with fish sauce, soy sauce, and sugar",
            "Toss in holy basil leaves and stir until wilted",
            "Serve immediately over steamed rice"
        ],
        cuisine: "Thai",
        preparationTime: 15,
        cookingTime: 10,
        servings: 4,
        difficulty: "Medium",
        tags: ["thai", "spicy", "chicken", "basil", "quick", "ai-generated"],
        estimatedCalories: 280,
        imageUrl: "https://via.placeholder.com/400x300?text=Thai+Basil+Chicken",
        userEmail: "foodie_lover@gmail.com",
        savedAt: new Date("2024-09-18T14:30:00.000Z"),
        syncedFromMobile: true,
        deviceInfo: {
            platform: "flutter",
            deviceId: "pixel6_emulator_001"
        }
    },
    {
        title: "Creamy Mushroom Risotto",
        description: "Rich and creamy Italian risotto with mixed mushrooms. AI-generated recipe with perfect texture and flavor balance.",
        ingredients: [
            "1½ cups Arborio rice",
            "4 cups warm chicken stock",
            "300g mixed mushrooms, sliced",
            "1 medium onion, finely diced",
            "3 cloves garlic, minced",
            "½ cup white wine",
            "50g butter",
            "100g Parmesan cheese, grated",
            "2 tbsp olive oil",
            "Fresh parsley, chopped",
            "Salt and black pepper to taste"
        ],
        instructions: [
            "Heat olive oil and half the butter in a heavy-bottomed pan",
            "Sauté mushrooms until golden, remove and set aside",
            "Add onion and garlic to the same pan, cook until soft",
            "Add rice and stir for 2 minutes until edges are translucent",
            "Pour in wine and stir until absorbed",
            "Add warm stock one ladle at a time, stirring constantly",
            "Continue until rice is creamy and al dente (about 18-20 minutes)",
            "Stir in remaining butter, mushrooms, and Parmesan",
            "Garnish with parsley and serve immediately"
        ],
        cuisine: "Italian", 
        preparationTime: 20,
        cookingTime: 25,
        servings: 6,
        difficulty: "Hard",
        tags: ["italian", "risotto", "mushroom", "creamy", "comfort-food", "ai-generated"],
        estimatedCalories: 420,
        imageUrl: "https://via.placeholder.com/400x300?text=Mushroom+Risotto",
        userEmail: "chef_mario@hotmail.com", 
        savedAt: new Date("2024-09-17T19:45:00.000Z"),
        syncedFromMobile: true,
        deviceInfo: {
            platform: "flutter",
            deviceId: "samsung_galaxy_s21"
        }
    },
    {
        title: "Korean Kimchi Fried Rice",
        description: "Flavorful Korean comfort food with fermented kimchi and perfectly fried rice. AI-optimized for maximum umami flavor.",
        ingredients: [
            "3 cups cooked day-old rice",
            "1 cup aged kimchi, chopped",
            "200g pork belly, diced",
            "2 green onions, sliced",
            "2 cloves garlic, minced",
            "1 tbsp gochujang paste",
            "2 tbsp kimchi juice",
            "1 tbsp sesame oil",
            "2 tbsp vegetable oil",
            "2 fried eggs for topping",
            "1 tsp sesame seeds"
        ],
        instructions: [
            "Heat vegetable oil in a large pan or wok",
            "Cook pork belly until crispy and golden",
            "Add garlic and kimchi, stir-fry for 2-3 minutes",
            "Add gochujang and kimchi juice, mix well",
            "Add day-old rice, breaking up clumps with spatula",
            "Stir-fry everything together for 5-6 minutes",
            "Drizzle with sesame oil and add green onions",
            "Top with fried eggs and sprinkle with sesame seeds"
        ],
        cuisine: "Korean",
        preparationTime: 15,
        cookingTime: 15, 
        servings: 2,
        difficulty: "Easy",
        tags: ["korean", "kimchi", "fried-rice", "pork", "spicy", "ai-generated"],
        estimatedCalories: 520,
        imageUrl: "https://via.placeholder.com/400x300?text=Kimchi+Fried+Rice",
        userEmail: "k_food_fan@yahoo.com",
        savedAt: new Date("2024-09-16T12:20:00.000Z"),
        syncedFromMobile: true,
        deviceInfo: {
            platform: "flutter",
            deviceId: "iphone_13_pro"
        }
    },
    {
        title: "Mediterranean Quinoa Bowl",
        description: "Healthy and nutritious bowl with quinoa, fresh vegetables, and Mediterranean flavors. AI-designed for optimal nutrition balance.",
        ingredients: [
            "1 cup quinoa, rinsed",
            "2 cups vegetable broth",
            "1 cucumber, diced",
            "2 tomatoes, chopped",
            "1 red onion, thinly sliced", 
            "100g feta cheese, crumbled",
            "50g Kalamata olives, pitted",
            "¼ cup fresh mint leaves",
            "¼ cup fresh parsley",
            "3 tbsp olive oil",
            "2 tbsp lemon juice",
            "1 tsp dried oregano",
            "Salt and pepper to taste"
        ],
        instructions: [
            "Cook quinoa in vegetable broth until tender and fluffy",
            "Let quinoa cool to room temperature",
            "Combine cucumber, tomatoes, and red onion in a large bowl",
            "Add cooled quinoa to the vegetable mixture",
            "Whisk together olive oil, lemon juice, and oregano for dressing", 
            "Pour dressing over quinoa salad and toss gently",
            "Top with crumbled feta, olives, mint, and parsley",
            "Season with salt and pepper, serve chilled"
        ],
        cuisine: "Mediterranean",
        preparationTime: 20,
        cookingTime: 15,
        servings: 4,
        difficulty: "Easy", 
        tags: ["mediterranean", "quinoa", "healthy", "vegetarian", "fresh", "ai-generated"],
        estimatedCalories: 340,
        imageUrl: "https://via.placeholder.com/400x300?text=Quinoa+Bowl",
        userEmail: "healthy_eater@gmail.com",
        savedAt: new Date("2024-09-15T10:15:00.000Z"),
        syncedFromMobile: true,
        deviceInfo: {
            platform: "flutter", 
            deviceId: "oneplus_9_pro"
        }
    },
    {
        title: "Chocolate Lava Cake",
        description: "Decadent individual chocolate cakes with molten centers. AI-perfected recipe for restaurant-quality dessert at home.",
        ingredients: [
            "100g dark chocolate (70%), chopped",
            "100g butter",
            "2 large eggs",
            "2 egg yolks",
            "60g caster sugar",
            "30g plain flour",
            "Pinch of salt",
            "Butter for ramekins",
            "Cocoa powder for dusting",
            "Vanilla ice cream for serving"
        ],
        instructions: [
            "Preheat oven to 200°C and butter 4 ramekins",
            "Dust ramekins with cocoa powder, shaking out excess",
            "Melt chocolate and butter in a double boiler until smooth",
            "In a separate bowl, whisk eggs, egg yolks, and sugar until thick",
            "Fold melted chocolate mixture into egg mixture",
            "Sift in flour and salt, fold gently until just combined",
            "Divide batter between prepared ramekins",
            "Bake for 12-14 minutes until edges are firm but centers jiggle",
            "Run a knife around edges and invert onto serving plates",
            "Serve immediately with vanilla ice cream"
        ],
        cuisine: "French",
        preparationTime: 15,
        cookingTime: 14,
        servings: 4,
        difficulty: "Medium",
        tags: ["french", "chocolate", "dessert", "lava-cake", "molten", "ai-generated"],
        estimatedCalories: 450,
        imageUrl: "https://via.placeholder.com/400x300?text=Lava+Cake",
        userEmail: "sweet_tooth@outlook.com",
        savedAt: new Date("2024-09-14T20:30:00.000Z"),
        syncedFromMobile: true,
        deviceInfo: {
            platform: "flutter",
            deviceId: "pixel_7_pro"
        }
    },
    {
        title: "Vietnamese Pho Bo",
        description: "Authentic Vietnamese beef noodle soup with rich bone broth. AI-enhanced traditional recipe with perfect spice balance.",
        ingredients: [
            "2kg beef bones",
            "500g beef brisket",
            "200g rice noodles",
            "1 large onion, halved",
            "5cm piece ginger",
            "3 star anise",
            "1 cinnamon stick",
            "1 tsp coriander seeds",
            "3 cloves",
            "2 tbsp fish sauce",
            "1 tbsp sugar",
            "200g raw beef sirloin, thinly sliced",
            "Fresh herbs: cilantro, mint, Thai basil",
            "Bean sprouts, lime wedges, chilies"
        ],
        instructions: [
            "Char onion and ginger over open flame until blackened",
            "Toast spices in a dry pan until fragrant",
            "Blanch beef bones in boiling water, then rinse clean",
            "Place bones, brisket, charred vegetables, and spices in a large pot",
            "Cover with water and simmer for 3-4 hours, skimming regularly",
            "Season broth with fish sauce and sugar",
            "Cook rice noodles according to package instructions",
            "Slice cooked brisket thinly",
            "Assemble bowls with noodles, cooked and raw beef",
            "Ladle hot broth over top and serve with fresh herbs and condiments"
        ],
        cuisine: "Vietnamese",
        preparationTime: 30,
        cookingTime: 240,
        servings: 6,
        difficulty: "Hard",
        tags: ["vietnamese", "pho", "beef", "noodles", "soup", "ai-generated"],
        estimatedCalories: 380,
        imageUrl: "https://via.placeholder.com/400x300?text=Pho+Bo",
        userEmail: "viet_food_lover@gmail.com",
        savedAt: new Date("2024-09-13T16:45:00.000Z"),
        syncedFromMobile: true,
        deviceInfo: {
            platform: "flutter",
            deviceId: "xiaomi_mi_11"
        }
    }
];

async function insertMobileAppAiRecipes() {
    try {
        console.log('� Creating mobile app users...');
        
        // Clear existing users and recipes
        await userModel.deleteMany({ email: { $in: mobileUsers.map(u => u.email) } });
        await savedAiRecipeModel.deleteMany({});
        
        // Create users first
        const createdUsers = {};
        for (const userData of mobileUsers) {
            const user = new userModel({
                name: userData.name,
                email: userData.email,
                phone: userData.phone,
                password: "password123", // Default password
                status: 1
            });
            
            const savedUser = await user.save();
            createdUsers[userData.email] = savedUser._id;
            console.log(`✅ Created user: ${userData.name} (${userData.email})`);
        }
        
        console.log('');
        console.log('📱 Inserting realistic mobile app AI recipes...');
        
        for (let i = 0; i < mobileAppAiRecipes.length; i++) {
            const recipeData = mobileAppAiRecipes[i];
            const userId = createdUsers[recipeData.userEmail];
            
            const savedRecipe = new savedAiRecipeModel({
                id: `mobile_ai_recipe_${Date.now()}_${i}`,
                ...recipeData,
                recipeCreatedAt: recipeData.savedAt,
                userId: userId,
                status: 'active',
                createdAt: recipeData.savedAt,
                updatedAt: recipeData.savedAt
            });
            
            await savedRecipe.save();
            console.log(`✅ Created: ${recipeData.title}`);
        }
        
        const totalSaved = await savedAiRecipeModel.countDocuments({ status: 'active' });
        
        console.log('');
        console.log('✨ Mobile app AI recipes inserted successfully!');
        console.log('');
        console.log('📊 Summary:');
        console.log(`   • Total recipes from mobile apps: ${totalSaved}`);
        console.log(`   • Users: ${mobileAppAiRecipes.length} different mobile users`);
        console.log(`   • Cuisines: Thai, Italian, Korean, Mediterranean, French, Vietnamese`);
        console.log(`   • All synced from Flutter mobile app`);
        console.log('');
        console.log('🌐 Admin Panel URL:');
        console.log('   • View saved recipes: http://localhost:3000/saved-ai-recipes');
        console.log('');
        console.log('🎉 Ready to view in admin panel!');
        
    } catch (error) {
        console.error('💥 Error inserting mobile app AI recipes:', error);
    }
    
    process.exit(0);
}

// Wait for DB connection then insert
setTimeout(insertMobileAppAiRecipes, 2000);