// Test script to simulate user creating AI recipe from Flutter mobile app
// This demonstrates the sync process from mobile app to admin panel

require('dotenv').config();
require('./config/conn');
const savedAiRecipeModel = require('./model/savedAiRecipeModel');
const userModel = require('./model/userModel');
const mongoose = require('mongoose');

async function testMobileUserCreateAIRecipe() {
    try {
        console.log('📱 Testing: Mobile User Creates New AI Recipe');
        console.log('=' .repeat(50));

        // Get a real user from database (simulate logged in mobile user)
        const user = await userModel.findOne({ email: 'huyplumber@gmail.com' });
        if (!user) {
            console.error('❌ User not found. Please make sure user exists in database.');
            process.exit(1);
        }

        console.log(`👤 Logged in user: ${user.firstname} ${user.lastname} (${user.email})`);

        // Simulate AI recipe generated by user on mobile
        const newAIRecipe = {
            id: `mobile_ai_recipe_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
            title: 'Cơm Chiên Hải Sản Cay',
            description: 'Món cơm chiên đậm đà hương vị với tôm, mực và gia vị cay nồng. Được tạo bởi AI dựa trên sở thích ẩm thực Việt Nam.',
            ingredients: [
                '300g cơm nguội',
                '150g tôm sú, bóc vỏ',
                '100g mực ống, thái khoanh',
                '2 quả trứng gà',
                '3 tép tỏi băm nhỏ',
                '1 củ hành tây thái nhỏ',
                '2 muỗng canh dầu ăn',
                '1 muỗng canh tương ớt',
                '1 muỗng cà phê đường',
                'Rau mùi, hành lá để trang trí',
                'Tiêu, muối vừa ăn'
            ],
            instructions: [
                'Làm nóng wok với dầu ăn trên lửa lớn',
                'Phi thơm tỏi và hành tây trong 1 phút',
                'Cho tôm và mực vào xào đến khi chín tái',
                'Đập trứng vào chảo, khuấy đều',
                'Thêm cơm nguội, dùng đũa tách đều các hạt cơm',
                'Nêm tương ớt, đường, muối và tiêu',
                'Xào đều trong 3-4 phút cho đến khi cơm nóng đều',
                'Tắt bếp, rắc rau mùi và hành lá'
            ],
            cuisine: 'Vietnamese',
            preparationTime: 15,
            cookingTime: 12,
            servings: 3,
            difficulty: 'Medium',
            tags: ['vietnamese', 'fried-rice', 'seafood', 'spicy', 'quick-meal', 'ai-generated'],
            imageUrl: 'https://via.placeholder.com/400x300?text=Seafood+Fried+Rice',
            estimatedCalories: 320,
            recipeCreatedAt: new Date(),
            userId: user._id,
            userEmail: user.email,
            deviceInfo: {
                platform: 'flutter',
                os: 'Android',
                version: '13',
                device: 'Samsung Galaxy S23'
            },
            status: 'active'
        };

        console.log(`🍳 Creating new AI recipe: "${newAIRecipe.title}"`);
        console.log(`📊 Details: ${newAIRecipe.servings} servings, ${newAIRecipe.preparationTime + newAIRecipe.cookingTime} mins, ${newAIRecipe.difficulty} difficulty`);

        // Step 1: Save to database (simulating mobile app sync)
        const savedRecipe = new savedAiRecipeModel(newAIRecipe);
        await savedRecipe.save();

        console.log('✅ Recipe saved to database successfully!');
        console.log(`📝 Recipe ID: ${savedRecipe._id}`);

        // Step 2: Verify in admin panel query
        const allRecipes = await savedAiRecipeModel.find({ status: 'active' })
            .populate('userId', 'firstname lastname email')
            .sort({ createdAt: -1 })
            .limit(5);

        console.log('\n🔍 Recent AI Recipes in Admin Panel:');
        console.log('=' .repeat(50));
        
        allRecipes.forEach((recipe, index) => {
            console.log(`${index + 1}. ${recipe.title}`);
            console.log(`   👤 User: ${recipe.userId?.firstname} ${recipe.userId?.lastname} (${recipe.userId?.email})`);
            console.log(`   🍽️  Cuisine: ${recipe.cuisine} | 👥 Servings: ${recipe.servings} | ⏱️  Time: ${recipe.preparationTime + recipe.cookingTime} mins`);
            console.log(`   📅 Created: ${recipe.createdAt?.toLocaleString()}`);
            console.log('');
        });

        console.log('🎉 SUCCESS: New mobile AI recipe appears in admin panel!');
        console.log('🌐 Admin Panel URL: http://localhost:3000/saved-ai-recipes');
        console.log('');
        console.log('🔄 Real App Flow:');
        console.log('   1. User generates AI recipe on Flutter mobile app');
        console.log('   2. Recipe saves to local SharedPreferences');
        console.log('   3. App calls sync API to send recipe to backend');
        console.log('   4. Backend saves to MongoDB savedairecipes collection');
        console.log('   5. Admin panel displays recipe in real-time');

    } catch (error) {
        console.error('❌ Error testing mobile AI recipe creation:', error.message);
        process.exit(1);
    } finally {
        process.exit(0);
    }
}

testMobileUserCreateAIRecipe();